intf_libs = # Interface dependencies.
impl_libs = # Implementation dependencies.
#import xxxx_libs += libcurl%lib{curl}

import intf_libs += libcurl%lib{curl}
import intf_libs += libca-certificates-curl%lib{ca-certificates-curl}
#import ca_certificates += libca-certificates-curl%lib{ca-certificates-curl}

# Public headers.
#
pub = [dir_path] ../../include/cpr/

include $pub

pub_hdrs = $($pub/ pub_hdrs)

lib{cpr}: $pub/{$pub_hdrs}

# Private headers and sources as well as dependencies.
#
lib{cpr}: {hxx cxx}{**} $impl_libs $intf_libs #$ca_certificates

# Build options.
#
out_pfx_inc = [dir_path] $out_root/include/
src_pfx_inc = [dir_path] $src_root/include/
out_pfx_src = [dir_path] $out_root/src/
src_pfx_src = [dir_path] $src_root/src/

cxx.poptions =+ "-I$out_pfx_src" "-I$src_pfx_src" \
                "-I$out_pfx_inc" "-I$src_pfx_inc"

obja{*}: cxx.poptions += -DCPR_STATIC_BUILD
objs{*}: cxx.poptions += -DCPR_SHARED_BUILD

# Export options.
#
lib{cpr}:
{
  cxx.export.poptions = "-I$out_pfx_inc" "-I$src_pfx_inc"
  cxx.export.libs = $intf_libs
}

liba{cpr}: cxx.export.poptions += -DCPR_STATIC
libs{cpr}: cxx.export.poptions += -DCPR_SHARED

# For pre-releases use the complete version to make sure they cannot
# be used in place of another pre-release or the final version. See
# the version module for details on the version.* variable values.
#
if $version.pre_release
  lib{cpr}: bin.lib.version = "-$version.project_id"
else
  lib{cpr}: bin.lib.version = "-$version.major.$version.minor"

# Don't install private headers.
#
hxx{*}: install = false
